/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class NativeSerialPort {
    static open(
        path: string,
        options: SerialPortOptions | undefined | null,
        callback: (err: Error | null, arg: Buffer) => void,
        channelCapacity: number,
    ): Promise<NativeSerialPort>
    /** Write all bytes to the serial port. */
    write(data: Buffer): Promise<void>
    /** Wrap [`SerialPort::write_request_to_send`]. */
    writeRequestToSend(level: boolean): Promise<void>
    /** Wrap [`SerialPort::write_data_terminal_ready`]. */
    writeDataTerminalReady(level: boolean): Promise<void>
    /** Abort the command/read task and mark closed. */
    close(): Promise<void>
}

export interface AvailablePort {
    portName: string
    portType: string
    usbVid?: number
    usbPid?: number
    serialNumber?: string
    manufacturer?: string
    product?: string
}

export declare function availablePorts(): Array<AvailablePort>

export interface SerialPortOptions {
    /** Defaults to 115_200. */
    baudRate?: number
    /**
     * Set the number of bits used to represent a character sent on the line.
     *
     * Defaults to 8.
     */
    dataBits?: 5 | 6 | 7 | 8
    /**
     * Set the type of parity to use for error checking.
     *
     * Defaults to "none".
     */
    parity?: 'none' | 'odd' | 'even'
    /**
     * Set the number of bits to use to signal the end of a character.
     *
     * Defaults to 1.
     */
    stopBits?: 1 | 2
    /**
     * Set the type of signalling to use for controlling data transfer.
     *
     * Defaults to "none".
     */
    flowControl?: 'none' | 'software' | 'hardware'
    /**
     * Set data terminal ready (DTR) to the given state when opening the device.
     *
     * If `None`, preserve the state of data terminal ready (DTR) when opening the device.
     */
    dtrOnOpen?: boolean
}
